### ISSUE TITLE
Live pages aren't properly scraped

### ISSUE THREAD

**Issue by paymog** [FarzamMohammadi/NYTScraper#3]
Pages like https://www.nytimes.com/live/2021/08/09/world/covid-delta-variant-vaccine/cases-in-the-united-states-rise-to-their-highest-levels-since-february aren't properly scraped and end up with empty content:

![image](https://user-images.githubusercontent.com/1986950/128916760-2452a9d8-0993-475c-98ca-02d519844c3b.png)

note that the url parsing is also broken for these.

We should probably just omit them entirely since we don't care about live data.

**Comment by FarzamMohammadi** [comment]
Live, interactive and article corrections have now been omitted.
